/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.7 at Tue May 16 18:29:07 2017. */

#ifndef PB_PROTO_FIRMWAREUPDATE_FIRMWARE_UPDATE_PB_H_INCLUDED
#define PB_PROTO_FIRMWAREUPDATE_FIRMWARE_UPDATE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Proto_FirmwareUpdate_Chunk_ModuleType {
    Proto_FirmwareUpdate_Chunk_ModuleType_FEP = 0,
    Proto_FirmwareUpdate_Chunk_ModuleType_WPL = 1,
    Proto_FirmwareUpdate_Chunk_ModuleType_PLD = 2
} Proto_FirmwareUpdate_Chunk_ModuleType;
#define _Proto_FirmwareUpdate_Chunk_ModuleType_MIN Proto_FirmwareUpdate_Chunk_ModuleType_FEP
#define _Proto_FirmwareUpdate_Chunk_ModuleType_MAX Proto_FirmwareUpdate_Chunk_ModuleType_PLD
#define _Proto_FirmwareUpdate_Chunk_ModuleType_ARRAYSIZE ((Proto_FirmwareUpdate_Chunk_ModuleType)(Proto_FirmwareUpdate_Chunk_ModuleType_PLD+1))

typedef enum _Proto_FirmwareUpdate_ChunkResponse_Status {
    Proto_FirmwareUpdate_ChunkResponse_Status_OK = 0,
    Proto_FirmwareUpdate_ChunkResponse_Status_ERROR_CRC = 1,
    Proto_FirmwareUpdate_ChunkResponse_Status_ERROR_WRITE = 2
} Proto_FirmwareUpdate_ChunkResponse_Status;
#define _Proto_FirmwareUpdate_ChunkResponse_Status_MIN Proto_FirmwareUpdate_ChunkResponse_Status_OK
#define _Proto_FirmwareUpdate_ChunkResponse_Status_MAX Proto_FirmwareUpdate_ChunkResponse_Status_ERROR_WRITE
#define _Proto_FirmwareUpdate_ChunkResponse_Status_ARRAYSIZE ((Proto_FirmwareUpdate_ChunkResponse_Status)(Proto_FirmwareUpdate_ChunkResponse_Status_ERROR_WRITE+1))

typedef enum _Proto_FirmwareUpdate_WplOption_ID {
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_0 = 0,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_1 = 1,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_2 = 2,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_3 = 3,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_4 = 4,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_5 = 5,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_6 = 6,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_7 = 7,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_8 = 8,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_9 = 9,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_10 = 10,
    Proto_FirmwareUpdate_WplOption_ID_SPEAKER_11 = 11,
    Proto_FirmwareUpdate_WplOption_ID_MASTER = 254
} Proto_FirmwareUpdate_WplOption_ID;
#define _Proto_FirmwareUpdate_WplOption_ID_MIN Proto_FirmwareUpdate_WplOption_ID_SPEAKER_0
#define _Proto_FirmwareUpdate_WplOption_ID_MAX Proto_FirmwareUpdate_WplOption_ID_MASTER
#define _Proto_FirmwareUpdate_WplOption_ID_ARRAYSIZE ((Proto_FirmwareUpdate_WplOption_ID)(Proto_FirmwareUpdate_WplOption_ID_MASTER+1))

typedef enum _Proto_FirmwareUpdate_WplOption_ModuleID {
    Proto_FirmwareUpdate_WplOption_ModuleID_FEP = 0,
    Proto_FirmwareUpdate_WplOption_ModuleID_Summit = 1,
    Proto_FirmwareUpdate_WplOption_ModuleID_DSP = 2
} Proto_FirmwareUpdate_WplOption_ModuleID;
#define _Proto_FirmwareUpdate_WplOption_ModuleID_MIN Proto_FirmwareUpdate_WplOption_ModuleID_FEP
#define _Proto_FirmwareUpdate_WplOption_ModuleID_MAX Proto_FirmwareUpdate_WplOption_ModuleID_DSP
#define _Proto_FirmwareUpdate_WplOption_ModuleID_ARRAYSIZE ((Proto_FirmwareUpdate_WplOption_ModuleID)(Proto_FirmwareUpdate_WplOption_ModuleID_DSP+1))

typedef enum _Proto_FirmwareUpdate_WplOption_PartID {
    Proto_FirmwareUpdate_WplOption_PartID_APP = 0,
    Proto_FirmwareUpdate_WplOption_PartID_MFG = 1,
    Proto_FirmwareUpdate_WplOption_PartID_DFS = 2,
    Proto_FirmwareUpdate_WplOption_PartID_SYSTEM_DATA = 3
} Proto_FirmwareUpdate_WplOption_PartID;
#define _Proto_FirmwareUpdate_WplOption_PartID_MIN Proto_FirmwareUpdate_WplOption_PartID_APP
#define _Proto_FirmwareUpdate_WplOption_PartID_MAX Proto_FirmwareUpdate_WplOption_PartID_SYSTEM_DATA
#define _Proto_FirmwareUpdate_WplOption_PartID_ARRAYSIZE ((Proto_FirmwareUpdate_WplOption_PartID)(Proto_FirmwareUpdate_WplOption_PartID_SYSTEM_DATA+1))

/* Struct definitions */
typedef struct _Proto_FirmwareUpdate_VersionInfo {
    pb_callback_t module;
/* @@protoc_insertion_point(struct:Proto_FirmwareUpdate_VersionInfo) */
} Proto_FirmwareUpdate_VersionInfo;

typedef struct _Proto_FirmwareUpdate_VersionInfo_Module {
    pb_callback_t name;
    pb_callback_t version;
    pb_callback_t metadata;
/* @@protoc_insertion_point(struct:Proto_FirmwareUpdate_VersionInfo_Module) */
} Proto_FirmwareUpdate_VersionInfo_Module;

typedef struct _Proto_FirmwareUpdate_ChunkResponse {
    bool has_status;
    Proto_FirmwareUpdate_ChunkResponse_Status status;
    uint32_t offset;
/* @@protoc_insertion_point(struct:Proto_FirmwareUpdate_ChunkResponse) */
} Proto_FirmwareUpdate_ChunkResponse;

typedef struct _Proto_FirmwareUpdate_WplOption {
    bool has_id;
    Proto_FirmwareUpdate_WplOption_ID id;
    bool has_moduleID;
    Proto_FirmwareUpdate_WplOption_ModuleID moduleID;
    bool has_partID;
    Proto_FirmwareUpdate_WplOption_PartID partID;
/* @@protoc_insertion_point(struct:Proto_FirmwareUpdate_WplOption) */
} Proto_FirmwareUpdate_WplOption;

typedef struct _Proto_FirmwareUpdate_Chunk {
    uint32_t totalSize;
    uint32_t offset;
    pb_callback_t data;
    bool has_crc;
    uint32_t crc;
    bool has_moduleType;
    Proto_FirmwareUpdate_Chunk_ModuleType moduleType;
    pb_size_t which_options;
    union {
        Proto_FirmwareUpdate_WplOption wplOption;
    } options;
/* @@protoc_insertion_point(struct:Proto_FirmwareUpdate_Chunk) */
} Proto_FirmwareUpdate_Chunk;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Proto_FirmwareUpdate_Chunk_init_default  {0, 0, {{NULL}, NULL}, false, 0, false, (Proto_FirmwareUpdate_Chunk_ModuleType)0, 0, {Proto_FirmwareUpdate_WplOption_init_default}}
#define Proto_FirmwareUpdate_ChunkResponse_init_default {false, (Proto_FirmwareUpdate_ChunkResponse_Status)0, 0}
#define Proto_FirmwareUpdate_VersionInfo_init_default {{{NULL}, NULL}}
#define Proto_FirmwareUpdate_VersionInfo_Module_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Proto_FirmwareUpdate_WplOption_init_default {false, (Proto_FirmwareUpdate_WplOption_ID)0, false, (Proto_FirmwareUpdate_WplOption_ModuleID)0, false, (Proto_FirmwareUpdate_WplOption_PartID)0}
#define Proto_FirmwareUpdate_Chunk_init_zero     {0, 0, {{NULL}, NULL}, false, 0, false, (Proto_FirmwareUpdate_Chunk_ModuleType)0, 0, {Proto_FirmwareUpdate_WplOption_init_zero}}
#define Proto_FirmwareUpdate_ChunkResponse_init_zero {false, (Proto_FirmwareUpdate_ChunkResponse_Status)0, 0}
#define Proto_FirmwareUpdate_VersionInfo_init_zero {{{NULL}, NULL}}
#define Proto_FirmwareUpdate_VersionInfo_Module_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define Proto_FirmwareUpdate_WplOption_init_zero {false, (Proto_FirmwareUpdate_WplOption_ID)0, false, (Proto_FirmwareUpdate_WplOption_ModuleID)0, false, (Proto_FirmwareUpdate_WplOption_PartID)0}

/* Field tags (for use in manual encoding/decoding) */
#define Proto_FirmwareUpdate_VersionInfo_module_tag 1
#define Proto_FirmwareUpdate_VersionInfo_Module_name_tag 1
#define Proto_FirmwareUpdate_VersionInfo_Module_version_tag 2
#define Proto_FirmwareUpdate_VersionInfo_Module_metadata_tag 3
#define Proto_FirmwareUpdate_ChunkResponse_status_tag 1
#define Proto_FirmwareUpdate_ChunkResponse_offset_tag 2
#define Proto_FirmwareUpdate_WplOption_id_tag    1
#define Proto_FirmwareUpdate_WplOption_moduleID_tag 2
#define Proto_FirmwareUpdate_WplOption_partID_tag 3
#define Proto_FirmwareUpdate_Chunk_wplOption_tag 6
#define Proto_FirmwareUpdate_Chunk_totalSize_tag 1
#define Proto_FirmwareUpdate_Chunk_offset_tag    2
#define Proto_FirmwareUpdate_Chunk_data_tag      3
#define Proto_FirmwareUpdate_Chunk_crc_tag       4
#define Proto_FirmwareUpdate_Chunk_moduleType_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t Proto_FirmwareUpdate_Chunk_fields[7];
extern const pb_field_t Proto_FirmwareUpdate_ChunkResponse_fields[3];
extern const pb_field_t Proto_FirmwareUpdate_VersionInfo_fields[2];
extern const pb_field_t Proto_FirmwareUpdate_VersionInfo_Module_fields[4];
extern const pb_field_t Proto_FirmwareUpdate_WplOption_fields[4];

/* Maximum encoded size of messages (where known) */
/* Proto_FirmwareUpdate_Chunk_size depends on runtime parameters */
#define Proto_FirmwareUpdate_ChunkResponse_size  8
/* Proto_FirmwareUpdate_VersionInfo_size depends on runtime parameters */
/* Proto_FirmwareUpdate_VersionInfo_Module_size depends on runtime parameters */
#define Proto_FirmwareUpdate_WplOption_size      7

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define FIRMWARE_UPDATE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
